# Small rounded corners for windows and floating polybar segments

corner-radius = 6

rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_HORZ'",
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_MAXIMIZED_VERT'",
];

shadow-radius = 10;
shadow-opacity = 0.2;
shadow-offset-x = 0;
shadow-offset-y = 3;

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;

backend = "glx";
vsync = true;

wintypes:
{
  dock = { shadow = true; };
};
