swipe:
  3:
    begin:
      command: xdotool keydown Alt
    right:
      update:
        command: xdotool key Tab
        interval: 5
    left:
      update:
        command: xdotool key Shift+Tab
        interval: 5
    end:
      command: xdotool keyup Alt
  4:
    left:
      command: "i3-msg workspace prev"
    right:
      command: "i3-msg workspace next"
    up:
      command: "/home/gerry/XDG_config/fusuma/open-launcher.sh"
    down:
      command: "xdotool key ctrl+alt+d && xdotool keydown alt keydown Tab keyup Tab keydown Shift keydown Tab keyup Tab keyup Shift keyup alt"
      interval: 2
      threshold: 0.1

pinch:
  2:
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl"
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl"
  4:
    in:
      command: "/home/gerry/XDG_config/fusuma/open-window-switcher.sh"
      threshold: 0.3

hold:
  4:
    command: "xdotool key super+Tab"

plugin:
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true

---
context:
  application:
    - rofi
    - Rofi
    - hyprlauncher
tap:
  2:
    command: "/home/gerry/XDG_config/fusuma/confirm-selection.sh"
