-- require('lspconfig').eslint.setup {
--     settings = {
--         eslint = {
--             autoFixOnSave = true,
--             format = {
--                 enable = true
--             }
--         }
--     }
-- }
