[Greeter]
background=/usr/share/backgrounds/gerry-login-wallpaper.jpg
background-color=#282828
content-align=center
draw-user-backgrounds=true
stretch-background-across-monitors=true
theme-name=Gruvbox-Dark-Soft
icon-theme-name=Gruvbox-Plus-Dark
font-name=Ubuntu 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
clock-format=%a %d %b, %H:%M
